### ISSUE TITLE
GIFs don't load on production and test deploy leaderboard

### ISSUE THREAD

**Issue by trevorkw7** [acmucsd/membership-portal-ui-v2#60]
### Issue
Although GIFs in the localhost leaderboard load properly, once deployed to [production](https://v2.members.acmucsd.com/leaderboard) or in the Vercel preview. 

### Troubleshooting observations

- When the AWS S3 bucket holding the image is loaded through the `/_next/image` for image optimization and resizing, it returns the following error:
<img width="520" alt="image" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/54345106/c4de4fc7-2621-4c50-a115-804a8a6fb7e0">

**Comment by SheepTester** [comment]
https://github.com/vercel/next.js/issues/34310 had a similar issue and suggests that the issue is with the deployment not NextJS. Is there a log with more details about the error?

I guess if the website is hosted on Vercel, they might use a different image optimizer than on localhost. [Vercel's documentation](https://vercel.com/docs/image-optimization/limits-and-pricing#limits) says they don't support .gif, but unsupported formats should be returned as-is
